// Milestone 2 report generator (docx-js) — lean revision
const fs = require('fs');
const ROOT = require('path').resolve(__dirname, '..');   // package root: <ROOT>/{scripts,artifacts,figures}
const D = require('docx');
const {Document, Packer, Paragraph, TextRun, HeadingLevel, AlignmentType, Table, TableRow, TableCell, WidthType,
  BorderStyle, ShadingType, ImageRun, PageBreak, Footer, PageNumber, LevelFormat} = D;
const FIG = ROOT+'/figures';
const dims = JSON.parse(fs.readFileSync(FIG + '/dims.json'));
const ord=n=>{n=Math.round(n);const s=['th','st','nd','rd'],v=n%100;return n+(s[(v-20)%10]||s[v]||s[0]);};
const SS=JSON.parse(fs.readFileSync(ROOT+'/artifacts/scale_shift.json','utf8'));
const RT = JSON.parse(fs.readFileSync(ROOT+'/artifacts/report_tables.json'));
const ST=RT.stat, MLB=RT.mordor_labels, RK=RT.stat.ranks, AK=RT.addr_kinds;
const CF = JSON.parse(fs.readFileSync(ROOT+'/artifacts/confound_diag.json'));
const AD = JSON.parse(fs.readFileSync(ROOT+'/artifacts/addenda.json'));
const ADM=AD.mordor.modality_ambiguity, ADC=AD.mordor.sysmon_range_ids_from_other_channels, ADB=AD.lmd_broadcast;
const pctM=(n)=>(100*n/AD.mordor.n_rows).toFixed(2);
const SM_EC_V=(()=>{const rows=fs.readFileSync(ROOT+'/artifacts/eda_stats_Mordor.csv','utf8').split('\n');const h=rows[0].split(',');const r=rows.map(l=>l.split(',')).find(c=>c[0]==='f_event_category');return Number(r[h.indexOf('effect_size')]).toFixed(2);})();
const PFX=(()=>{const g={};AD.lmd_broadcast.own_host_prefixes_24.forEach(p=>{const a=p.split('.');const k=a[0]+'.'+a[1];(g[k]=g[k]||[]).push(+a[2]);});return Object.entries(g).map(([k,v])=>v.length>1?`${k}.{${v.sort((x,y)=>x-y).join(', ')}}.0/24`:`${k}.${v[0]}.0/24`).join(' and ');})();
const INK='0b0b0b', INK2='3f3f3f', ACC='1f4e79', HEADBG='1f4e79', ZEBRA='f2f5fb', FONT='Calibri';
const f3=(x)=>Number(x).toFixed(3), f4=(x)=>Number(x).toFixed(4), f2=(x)=>Number(x).toFixed(2);

// ---------- helpers ----------
const fixminus=(x)=>typeof x==='string'?x.replace(/(^|[\s(=])-(\d)/g,'$1\u2212$2'):x;
function t(text,o={}){return new TextRun({text:fixminus(text),font:FONT,size:o.size||20,bold:o.bold,italics:o.italics,color:o.color||INK});}
function p(runs,o={}){ if(typeof runs==='string') runs=[t(runs,o)];
  return new Paragraph({children:runs,spacing:{line:o.line||360,after:o.after==null?80:o.after,before:o.before||0},alignment:o.align,keepNext:o.keepNext});}
function h1(x,pb){return new Paragraph({heading:HeadingLevel.HEADING_1,spacing:{before:pb?0:300,after:90},keepNext:true,pageBreakBefore:!!pb,children:[new TextRun({text:x,font:FONT,size:29,bold:true,color:ACC})]});}
function h2(x){return new Paragraph({heading:HeadingLevel.HEADING_2,spacing:{before:140,after:60},children:[new TextRun({text:x,font:FONT,size:24,bold:true,color:INK})]});}
function h3(x){return new Paragraph({heading:HeadingLevel.HEADING_3,spacing:{before:120,after:60},children:[new TextRun({text:x,font:FONT,size:22,bold:true,color:INK2})]});}
function bullet(runs){return new Paragraph({numbering:{reference:'bl',level:0},spacing:{line:330,after:40},children:typeof runs==='string'?[t(runs)]:runs});}
const TS=9940/9360;   // table widths were laid out for a 6.5-inch column; scale to the 6.69-inch column
function cell(content,w,o={}){ w=Math.round(w*TS); const kids=Array.isArray(content)?content:[content];
  const paras=kids.map(c=> typeof c==='string'? new Paragraph({keepNext:o.keepNext,children:[new TextRun({text:fixminus(c),font:FONT,size:o.size||17,bold:o.bold,color:o.color||INK})],spacing:{line:235,after:15,before:15},alignment:o.align}):c);
  return new TableCell({width:{size:w,type:WidthType.DXA},shading:o.fill?{type:ShadingType.CLEAR,fill:o.fill,color:'auto'}:undefined,margins:{top:35,bottom:35,left:80,right:80},verticalAlign:'center',children:paras});}
function headerRow(labels,widths){return new TableRow({tableHeader:true,cantSplit:true,children:labels.map((l,i)=>cell(l,widths[i],{bold:true,color:'ffffff',fill:HEADBG,size:17}))});}
function table(widths,rows){widths=widths.map(w=>Math.round(w*TS));return new Table({columnWidths:widths,width:{size:widths.reduce((a,b)=>a+b,0),type:WidthType.DXA},
  borders:{top:{style:BorderStyle.SINGLE,size:2,color:'bfbfbf'},bottom:{style:BorderStyle.SINGLE,size:2,color:'bfbfbf'},left:{style:BorderStyle.SINGLE,size:2,color:'bfbfbf'},right:{style:BorderStyle.SINGLE,size:2,color:'bfbfbf'},insideHorizontal:{style:BorderStyle.SINGLE,size:2,color:'d9d9d9'},insideVertical:{style:BorderStyle.SINGLE,size:2,color:'d9d9d9'}},rows});}
function drow(cells,widths,i,o={}){const longest=Math.max(...cells.map(c=>String(c).length)); return new TableRow({cantSplit:longest<260,children:cells.map((c,j)=>cell(c,widths[j],{size:o.size||17,fill:(i%2===1)?ZEBRA:undefined,bold:o.boldCol0&&j===0,keepNext:false,align:((o.centerFrom!=null&&j>=o.centerFrom)&&!(o.leftCols||[]).includes(j))?AlignmentType.CENTER:undefined}))});}
function tcap(n,x){const para=new Paragraph({keepNext:true,keepLines:true,spacing:{before:120,after:50},children:[new TextRun({text:`Table ${n}. `,font:FONT,size:17,bold:true,color:INK2}),new TextRun({text:fixminus(x),font:FONT,size:17,italics:true,color:INK2})]}); para.__tcap=true; return para;}
function figure(name,n,cap,targetW){const [w,h]=dims[name];const W=Math.min(targetW||624,624);const H=Math.round(h*W/w);
  return [new Paragraph({keepNext:true,alignment:AlignmentType.CENTER,spacing:{before:80,after:30},children:[new ImageRun({type:'png',data:fs.readFileSync(`${FIG}/${name}`),transformation:{width:W,height:H}})]}),
          new Paragraph({alignment:AlignmentType.CENTER,spacing:{after:140},children:[new TextRun({text:`Figure ${n}. `,font:FONT,size:17,bold:true,color:INK2}),new TextRun({text:cap,font:FONT,size:17,italics:true,color:INK2})]})];}
const C=[];
const S=RT.summary, SP=RT.split, ML=RT.meta.LMD, MM=RT.meta.Mordor;

// ===================== TITLE PAGE =====================
C.push(new Paragraph({spacing:{before:1500},alignment:AlignmentType.CENTER,children:[new TextRun({text:'Course: AI-Driven Intrusion and Malware Detection',font:FONT,size:24,color:INK2})]}));
C.push(new Paragraph({spacing:{before:120},alignment:AlignmentType.CENTER,children:[new TextRun({text:'Technical Report — Milestone 2',font:FONT,size:26,bold:true,color:INK2})]}));
C.push(new Paragraph({spacing:{before:240,after:80},alignment:AlignmentType.CENTER,children:[new TextRun({text:'AI-Driven Detection of Lateral Movement',font:FONT,size:44,bold:true,color:ACC})]}));
C.push(new Paragraph({spacing:{after:60},alignment:AlignmentType.CENTER,children:[new TextRun({text:'MITRE ATT&CK TA0008 — T1021 Remote Services · T1210 Exploitation of Remote Services · T1550 Use of Alternate Authentication Material · T1570 Lateral Tool Transfer',font:FONT,size:20,italics:true,color:INK2})]}));
C.push(new Paragraph({spacing:{before:100,after:40},alignment:AlignmentType.CENTER,border:{bottom:{style:BorderStyle.SINGLE,size:6,color:ACC}},children:[t('')]}));
C.push(new Paragraph({spacing:{before:160,after:40},alignment:AlignmentType.CENTER,children:[new TextRun({text:'Team Members',font:FONT,size:20,bold:true,color:INK2})]}));
['Ela Ambar Grynbaum — ela.ambar2306@gmail.com','Daniel Shostak — danshostak0@gmail.com','Itamar Tsafrir Ornstein — itamarit77@gmail.com','Itamar Klartag — itamarklartag@gmail.com']
 .forEach(m=>C.push(new Paragraph({alignment:AlignmentType.CENTER,spacing:{after:30},children:[t(m,{size:20})]})));
C.push(new Paragraph({spacing:{before:200},alignment:AlignmentType.CENTER,children:[t('Datasets: LMD-2023 (Sysmon)  •  OTRF Mordor APT29 (Sysmon + Windows Security + System)',{size:20,color:INK2})]}));
C.push(new Paragraph({alignment:AlignmentType.CENTER,children:[t('Date of Submission: 27 September 2026',{size:20,color:INK2})]}));
C.push(new Paragraph({spacing:{before:700},alignment:AlignmentType.CENTER,children:[t('1.5 line spacing, 10 pt body; reproducibility notes and feature registry in Appendix A; figures in Appendix B.',{size:18,color:INK2})]}));
C.push(new Paragraph({children:[new PageBreak()]}));

// ===================== CHAPTER 1 =====================
C.push(h1('Chapter 1 — Threat Characterization and Telemetry Mapping (Step 1)'));
C.push(h2('1.1 Deep-Dive Threat Analysis'));
C.push(p([t('Scope. ',{bold:true}),t('Lateral Movement (TA0008) as ATT&CK defines it [7], covering the four techniques our two datasets record: '),t('T1210 Exploitation of Remote Services',{bold:true}),t(' (the LMD-2023 “EoRS” class: MS17-010/EternalBlue, BlueKeep, SMBGhost, SMBleed, Log4Shell, Zerologon, …), '),t('T1021 Remote Services',{bold:true}),t(' (SMB/admin shares, RPC/DCOM, WinRM, RDP — the Mordor APT29 pivots), '),t('T1550 Use of Alternate Authentication Material',{bold:true}),t(' (pass-the-hash / pass-the-ticket — the LMD-2023 “EoHT” class, together with the credential-access precursors that can precede it) and '),t('T1570 Lateral Tool Transfer',{bold:true}),t('. Exploit-based and credential-based pivots differ in how they gain execution but share the post-access footprint — inbound remote-service traffic, a service- or WMI-hosted child process, tool drops, credential access — and that footprint is what is engineered; payload signatures are not, because neither dataset contains packet payloads.')]));
C.push(p([t('Mechanics on two planes. ',{bold:true}),t('An adversary with valid or forged credentials (or an exploit) reaches a remote host, invokes a remote-execution service and runs a payload. On the '),t('network plane',{italics:true}),t(' the source host opens a short-lived outbound connection to an administrative port (445, 135 + dynamic RPC, 5985/5986, 3389). On the '),t('host plane of the destination',{italics:true}),t(' the connection arrives as a network logon (Security 4624 type 3 for SMB/RPC/WinRM, type 10 for RDP); an explicit-credential logon 4648 is recorded on the source host that supplied the credentials and a Kerberos service-ticket request 4769 on the domain controller; a service or WMI/WinRM host process — services.exe, wmiprvse.exe, wsmprovhost.exe — spawns an interpreter (cmd.exe, powershell.exe, rundll32.exe); a service may be registered (System 7045); a tool may be written to ADMIN$/C$ (Security 5145; Sysmon 11 on the destination). For T1550 the credential material is first obtained on an already-compromised host, typically by opening LSASS with memory-read rights (Sysmon 10, GrantedAccess 0x1010/0x1410 — an access request, not a confirmed dump; the T1003 stage that precedes a pass-the-hash logon, not the pivot itself). A detector that watches one plane sees half the trail.')]));
C.push(p([t('Correlating the planes. ',{bold:true}),t('Source-side evidence (an outbound admin-port connection on host A) and destination-side evidence (an inbound admin-port connection followed by a remote-execution parent→child spawn on host B) are different observations, so both are computed: per host, the rate of all admin-port connections and of its inbound subset, the outbound fan-out (distinct destinations of connections the host initiated) and the inbound peer diversity (distinct remote addresses that connected or logged on to it), plus a destination-side flag that fires when a remote-execution-hosted child is spawned while the host’s trailing inbound admin-port count is positive. Cross-host stitching of A’s outbound to B’s inbound event by (SourceIp, DestinationIp, time) is specified as a later step (Table 10) and not claimed here. Trailing-window rate, fan-out and out-degree features cover both the slow hands-on pivot and the automated sweep; single-event fields cover neither.')]));

C.push(h2('1.2 Telemetry & Feature Mapping List'));
C.push(p(`Table 1 maps each adversarial behaviour to its telemetry source (event semantics per the Sysmon and Windows security-auditing references [10]), the raw fields, the engineered feature(s) and the relationship. (H) host-plane, (N) network-plane, (X) aggregate. The candidate pool holds ${RT.n_pool} features (count taken from the code); definitions follow in §1.3.`,{after:70}));
const W1=[1650,1250,1600,2050,2810];
const T1=[
 ['Multi-host pivot / fan-out sweep (X)','Sysmon EID 3 (Initiated = true for the fan-out counts; both directions for adminport_conn_60s)','Computer, DestinationIp, DestinationPort, SystemTime','distinct_dstip_300s, distinct_dstport_300s, adminport_conn_60s','Automated pivoting touches many distinct destinations/admin ports in a tight window; a hands-on pivot shows a small burst of new pairings.'],
 ['Destination receives remote-service traffic (N→H)','Sysmon EID 3 (Initiated = false); Security 4624, 4648, 5140, 5145 client IpAddress','DestinationPort, Initiated, SourceIp, IpAddress','inbound_adminport_60s, inbound_peers_300s','Bursts of inbound admin-port connections, and an unusual number of distinct remote peers reaching a host, are the destination-side signature of being pivoted to.'],
 ['Remote-execution lineage on the destination (H)','Sysmon EID 1','ParentImage → Image, IntegrityLevel','lolbin_parent_child, remote_exec_parent, remote_exec_after_inbound, integrity_high','services.exe / wmiprvse.exe / wsmprovhost.exe spawning an interpreter fingerprints PsExec-, WMI- or WinRM-style execution; remote_exec_after_inbound ties it to an inbound admin-port connection on the same host within 60 s.'],
 ['Machine-speed execution velocity (X)','all Sysmon events (rate, Δt); EID 1 / EID 3 (per-type rates)','SystemTime, Computer','host_evt_rate_60s, host_proc_create_60s, host_netconn_60s, inter_event_dt_log','Per-host trailing rates and inter-event deltas separate automated tooling from human-paced administration.'],
 ['Graph topology & rare pairings (X)','Sysmon EID 3 (Initiated = true)','Computer, DestinationIp','host_out_degree_1h, rare_dst_pair','Out-degree spikes on endpoints and never-before-seen (host, destination) edges are the peer-group deviations of a pivot.'],
 ['Remote service exploitation over admin ports (N)','Sysmon EID 3','DestinationPort, Initiated, SourceIsIpv6','admin_port_flag, initiated, is_ipv6','LM rides SMB/RPC/WinRM/RDP; an outbound-initiated connection from a workstation to an admin port is the network doorway.'],
 ['LOLBin & obfuscated command execution (H)','Sysmon EID 1 (CommandLine); any Sysmon event carrying Image','Image, CommandLine','image_is_lolbin, cmdline_len, cmdline_entropy, cmdline_susp','Native admin binaries with encoded/hidden flags; length, entropy and token flags capture obfuscation regardless of transport.'],
 ['Lateral tool transfer — T1570 (H)','Sysmon EID 11 (TargetFilename); any Sysmon event carrying Image','TargetFilename, Image','exec_file_drop, file_drop_staging, exec_from_staging','.exe/.dll/.ps1 written to admin shares or staging paths (\\Windows\\Temp, \\Users\\Public); exec_from_staging marks every event of a process whose image runs from such a path.'],
 ['Possible credential harvesting preceding T1550 (H)','Sysmon EID 10','TargetImage, GrantedAccess','lsass_access, cred_access_mask','Credential material is read from process memory on an already-compromised host (access requests, not confirmed dumps): a possible harvesting stage before a pass-the-hash pivot, not the pivot itself (definitions in §1.3).'],
 ['Authentication & service-control — Security auditing (H)','Security 4624, 4648, 4769, 5145; System 7045, Security 4697','LogonType, TargetServerName, ShareName, RelativeTargetName','network_logon_t3, explicit_cred_4648, kerberos_tgs_4769, admin_share_access, service_install','Network logon (type 3, not RDP type 10), alternate credentials, service tickets, ADMIN$/C$/IPC$ access, remote service registration. Collected in Mordor only; absent from Sysmon-only LMD (§3–5).'],
 ['Anomalous user context (X)','any event carrying User','User, Computer','distinct_users_60s','Remote execution under a stolen or service token adds distinct principals on a host inside a short window.'],
 ['Off-baseline timing (X) — audit only, not a model input','SystemTime','time of day, weekday','seconds_in_day, diurnal_sin, diurnal_cos, weekday, is_business_hours','Each encodes the capture schedule in at least one dataset (§3.3); kept in the candidate pool only to measure that leakage, excluded from the prospective model schema (§5.1).'],
 ['Telemetry availability (X)','all channels','Channel, EventID','sec_observed, net_observed','1 from the host’s first authentication/service event (IDs in Table 10) / first EID 3 onward (causal running maximum): separates a recorded zero from a modality not yet observed.'],
 ['Event semantics (X)','all channels','Channel, EventID','event_category','Semantic category of the current event (process, network, logon, share, service, …) as multi-stage context; one-hot for distance-based models.'],
 ['Control: PID = ExecutionPID (H)','Sysmon header vs EventData','ProcessId (EventData) vs Execution.ProcessID (header)','naive_relational_pid','The previous submission’s feature, kept as a control: equality of the logging process’s header PID with the EventData PID carries no lineage (§4.2: a null-fill artefact).'],
];
const t1=[headerRow(['Adversarial behavioural characteristic','Telemetry source','Raw log fields','Engineered feature(s)','Relationship'],W1)];
T1.forEach((r,i)=>t1.push(drow(r,W1,i,{size:15})));
C.push(table(W1,t1)); C.push(tcap(1,`Telemetry & Feature Mapping List (${RT.n_pool}-feature candidate pool grouped into ${t1.length-1} behavioural characteristics).`));

C.push(h2('1.3 Theoretical Feature Rationale'));
C.push(bullet([t('Trailing-window rates and fan-out (causal). ',{bold:true}),t('rate(h,t;Δ) = |{e : host(e)=h, t−Δ < time(e) ≤ t}| for Δ = 60 s (all events; process creations; network connections; connections to an admin port, i.e. destination port ∈ {'+AD.lmd_broadcast.admin_port.admin_ports.join(', ')+'} — SMB, RPC, WinRM and RDP plus the Kerberos/LDAP ports a pivot touches on the domain controller; inbound admin-port connections). Direction is taken from Initiated: Sysmon writes DestinationIp = the monitored host for an inbound connection, so a remote destination exists only when Initiated = true, and the remote peer of an inbound connection is SourceIp (for a Security logon/share event, the client IpAddress). fanout(h,t;300 s) = |{dst(e)}| over the trailing 5-minute window of outbound connections, for destination IP (unicast only, below) and for destination port (all outbound connections); out-degree(h,t;3600 s) likewise over one hour; inbound_peers(h,t;300 s) = |{peer(e)}| over inbound connections and logons; rare_dst_pair = 1 on the first occurrence of an outbound (h, dst) edge. Only unicast, non-loopback addresses count as destinations or peers: broadcast, multicast (224.0.0.0/4, ff00::/8) and loopback traffic is NetBIOS/SSDP-style chatter, not a host that can be pivoted to (§3.3 quantifies its share). The .255 rule for broadcast is mask-dependent in general but exact here: every .255 address observed is the broadcast address of a /24 network holding a monitored host ('+ADB.own_host_prefixes_24.length+' in LMD, '+AD.mordor.broadcast.n_255_addresses+' in Mordor) or the link-local 169.254.255.255 (artifacts/addenda.json). All windows contain only current and past events of the same host, so no aggregate is informed by later events.')]));
C.push(bullet([t('Temporal. ',{bold:true}),t('Δtᵢ = time(eᵢ) − time(eᵢ₋₁) per host, stored as log(1+Δt) — Paper A’s “time difference” computed from timestamps. The cyclical pair (sin 2πs/86400, cos 2πs/86400) of seconds-in-day s is audit-only, like every absolute-time feature (§3.3.1).')]));
C.push(bullet([t('Lineage and correlation. ',{bold:true}),t('lolbin_parent_child = [basename(ParentImage) ∈ {services.exe, wmiprvse.exe, wsmprovhost.exe, mmc.exe, psexesvc.exe, winrshost.exe, …} ∧ basename(Image) ∈ {cmd.exe, powershell.exe, rundll32.exe, wmic.exe, …}]; remote_exec_parent = [basename(ParentImage) ∈ that service/WMI/WinRM/scheduler host set]; remote_exec_after_inbound = [remote_exec_parent = 1 ∧ inbound_adminport_60s > 0] on the same host; image_is_lolbin = [basename(Image) ∈ the interpreter set ∪ {psexec.exe, paexec.exe, winrs.exe, vssadmin.exe, ntdsutil.exe, …}]; integrity_high = [IntegrityLevel ∈ {High, System}]; distinct_users_60s = |{user(e)}| over the trailing 60 s of the host.')]));
C.push(bullet([t('Command line. ',{bold:true}),t('Length; Shannon entropy H = −Σ pᵢ log₂ pᵢ over the character distribution; token flag for PowerShell encoding, hidden-window, policy-bypass and download idioms (-enc, -w hidden, -ep bypass, FromBase64String, DownloadString, Net.WebClient, stand-alone IEX, …) and admin-share paths; bare generic tokens such as “iex” or “webclient” are avoided because they match iexplore.exe and the WebClient service host.')]));
C.push(bullet([t('Credential harvesting. ',{bold:true}),t(`lsass_access = [EID 10 ∧ TargetImage = lsass.exe]; cred_access_mask = [EID 10 ∧ GrantedAccess ∈ {0x1010, 0x1410, 0x1438, 0x143A, 0x1F1FFF, 0x1FFFFF}] on any target process — the memory-read access masks that credential dumpers request. Sysmon 10 records the access request, not a confirmed read, so both mark a possible harvesting stage (LMD: ${ST.lmd_lsass_attack_pct.toFixed(2)}% and ${ST.lmd_credmask_attack_pct.toFixed(1)}% of attack rows; benign LMD holds ${ST.lmd_benign_eid10_rows===1?'one EID 10 row':ST.lmd_benign_eid10_rows+' EID 10 rows'} in total, §4.2).`)]));
C.push(bullet([t('Tool transfer and staging. ',{bold:true}),t('exec_file_drop = [EID 11 ∧ TargetFilename ends in .exe, .dll, .bat, .ps1, .vbs, .scr, .cmd, .hta, .jar, .psm1 or .com]; file_drop_staging = [EID 11 ∧ TargetFilename under a staging path: \\Windows\\Temp, \\Temp, \\Tmp, \\Users\\Public, \\PerfLogs, \\AppData, \\ProgramData, \\Downloads, \\\u2060$Recycle.Bin, \\Windows\\Debug or \\Windows\\Tasks]; exec_from_staging = [Image under a staging path], on every event of that process.')]));
C.push(bullet([t('Field applicability. ',{bold:true}),t('Each Sysmon field is masked to the event types whose schema defines it (ParentImage/CommandLine → EID 1 and Security 4688; IntegrityLevel → EID 1; DestinationIp/Port/Initiated → EID 3; SourceIp / client IpAddress → EID 3 and Security 4624, 4648, 5140, 5145; TargetImage → EID 10, 8 and Security 4648; GrantedAccess → EID 10; TargetFilename → EID 11, 23, 26, 2, 15 and Security 5140, 5145; Image is left on every event that records the acting process), and the placeholder “0” that the LMD-2023 export writes into empty fields is treated as missing; otherwise placeholder equality creates spurious features (§4.2).')]));

// ===================== CHAPTER 2 =====================
C.push(h1('Chapter 2 — Academic Literature Review and Feature Extraction (Step 2)'));
C.push(h2('2.1 Literature Extraction Matrix'));
const W2=[1800,2250,5310];
const T2=[
 ['Paper A — Bai et al., Computer Communications 165:9–19, 2021 [1]','Proposed: LogitBoost (decision-tree base, ≈100 estimators). Baselines: RF, LightGBM, Gaussian NB, feed-forward NN, LR, DT; compared with Kaiafas et al.; 10-fold CV.','12 fields from Windows logon/logoff on LANL (56,837 reconstructed RDP sessions): 3 identity fields (user, source, destination — removed in the robustness model) and 9 derived: session duration D = t₄₆₃₄ − t₄₆₂₄; per-entity delta Δtᵢ = tᵢ − tᵢ₋₁ for user, source, destination; mean session duration per entity (μₑ over all sessions containing the entity); weekday; seconds-in-day. No scaling.'],
 ['Paper B — Smiliotopoulos & Kambourakis, Int. J. Inf. Secur. 25(1):38, 2026 [3]','13 algorithms (9 shallow incl. Bagging-LightGBM and Extra Trees; 4 DNN incl. LSTM) under 16 resampling scenarios (over-, under- and hybrid-sampling).','8 Sysmon fields by PCA loading from LMD-2023’s 93 columns: CompSTA, DstPortName, EventID, Init, SrcIpv6, EventRecID, ExecProcessID, ProcessId; one-hot encoded; scalers/resamplers fit on training folds; LSTM consumes the per-event vector (T = 1).'],
 ['Context — Smiliotopoulos et al., IJIS 22(6):1893–1919, 2023 [2] (LMD-2023 origin)','RF, ExtraTrees, LightGBM, DT, kNN, NB; LSTM, CNN, RNN, AE. Hand-set hyper-parameters (its own Table 10: RF 1,000 trees; LightGBM max_depth 20, 100 estimators; DT max_depth 20; kNN k = 10), no automated tuning.','15 columns: EventID, Initiated, SourceIpv6, DestinationPortName, ProcessId, ExecutionProcessID, EventRecordID, Computer and seven SystemTime components (year, month, week, day, hour, minute, day-of-week).'],
];
const t2=[headerRow(['Paper','Models','Features and their mathematical / encoding representation'],W2)];
T2.forEach((r,i)=>t2.push(drow(r,W2,i,{size:15})));
C.push(table(W2,t2)); C.push(tcap(2,'Literature extraction matrix with explicit feature representations (verified against the primary sources where the full text was available; Table 12).'));

C.push(h2('2.2 Comparative Analytical Essay'));
C.push(p([t('(1) Semantic meaning. ',{bold:true}),t('Paper A (Table 2) assigns '),t('temporal-behavioural',{italics:true}),t(' meaning: session duration and inter-event deltas encode the tempo and regularity of remote logons against a per-entity mean duration μₑ (computed over all of the entity’s sessions in the cited study); weekday and seconds-in-day encode when work normally happens. Paper B assigns '),t('structural-operational',{italics:true}),t(' meaning: EventID, destination port and process-id fields record which service was touched, over which protocol, by which process; Init and SrcIpv6 give direction and address family. In short, behaviour over time versus structure per event.')]));
C.push(p([t('(2) Contrast. ',{bold:true}),t('Paper A (authentication plane) '),t('derives',{italics:true}),t(' metrics from timestamps, removes identity fields to prevent lab memorisation, synthesises durations for the red-team sessions, which lack logoff records, from the benign duration distribution, and finds shallow boosting best. Paper B (host plane) '),t('retains',{italics:true}),t(' raw categorical fields including the host identifier CompSTA, uses 16 resamplers, and finds shallow ensembles and DNNs both viable once resampled. Its identifier fields (CompSTA, EventRecordID, raw PIDs), the seven calendar columns of its predecessor [2] and its per-event LSTM (T = 1) are the choices our analysis contradicts (§3.3, §6.1).')]));
C.push(p([t('(3) Adopt / derive / reject. ',{bold:true}),t('The governing rule: derive behavioural metrics from raw fields rather than discard them because a turnkey column is absent (Table 3).')]));
const W3=[1600,2600,5160];
const T3=[
 ['Adopt','initiated, is_ipv6; seconds_in_day, weekday, is_business_hours and the cyclical pair (Paper A’s calendar fields, audit only)','Directly available; the time features are kept only to measure leakage (§3.3.1).'],
 ['Derive (Paper A concepts)','inter_event_dt_log, host_*_60s rates, distinct_dstip/port_300s, inbound_peers_300s, adminport_conn_60s, inbound_adminport_60s','Session-duration / time-difference ideas generalised to Sysmon as trailing per-host deltas, rates and fan-out from SystemTime.'],
 ['Derive (Paper B fields → lineage)','lolbin_parent_child, remote_exec_parent, remote_exec_after_inbound, image_is_lolbin; admin_port_flag','ProcessId/ExecutionProcessID replaced by the parent→child transition ParentImage→Image and its correlation with inbound admin-port traffic; Paper B’s DstPortName reduced to an admin-port indicator.'],
 ['Derive (new)','host_out_degree_1h, rare_dst_pair, distinct_users_60s, cmdline_*, exec_from_staging, exec_file_drop, file_drop_staging, lsass_access, cred_access_mask, integrity_high','Graph, user-context, command-line, T1570 and T1550 signals neither paper engineered; Kushwaha et al. [5] motivate the window/baseline forms.'],
 ['Adopt where collected','network_logon_t3, explicit_cred_4648, kerberos_tgs_4769, admin_share_access, service_install; sec_observed, net_observed','Paper A’s authentication plane engineered from Security events; populated on Mordor, absent from Sysmon-only LMD, carried with the two (new) observed-modality indicators.'],
 ['Encode','event_category','EventID mapped to semantic categories: integer code in the Chapter-4 trees (order caveat, §5.3), one-hot for distance-based models and the LSTM.'],
 ['Reject','CompSTA, EventRecordID, raw ProcessId/ExecutionProcessID, SystemTime year/month/week/day','Identifiers memorise the lab; raw PIDs are transient handles; calendar columns leak the capture schedule (§3.3). naive_relational_pid is kept only as a control.'],
];
const t3=[headerRow(['Decision','Feature(s)','Reasoning'],W3)];
T3.forEach((r,i)=>t3.push(drow(r,W3,i,{size:15,boldCol0:true})));
C.push(table(W3,t3)); C.push(tcap(3,'Adopt / derive / reject decisions.'));

// ===================== CHAPTER 3 =====================
C.push(h1('Chapter 3 — Exploratory Data Analysis and Domain Justification (Step 3)'));
C.push(h2('3.1 Statistical and Visual Exploration: datasets, labels and capture structure'));
C.push(p([t('Table 4 summarises both captures; Figs. 1–5 (Appendix B) are the visual exploration.')]));
const W4=[1900,3730,3730];
const T4=[
 ['Source','Raw labelled CSV “LMD-2023 [1.75M Elements][Labelled]checked.csv”, 94 columns (93 fields + Label), Sysmon only [2, 9]',`OTRF Security-Datasets APT29 day-1 + day-2 host JSON: Sysmon, Security, PowerShell, System channels [8]. Event numbers are read per channel — only Sysmon and Security IDs and System 7045 are mapped; the ${ADC.n_rows} rows (${ADC.pct_rows}%) that other channels log under Sysmon-range numbers (System 1/3/6/10–14/16/18/20/25, TerminalServices 21–24) are category “other” and enter no EID-keyed count.`],
 ['Rows used','1,752,836 records, none dropped (1,752,891 file lines: header, records, 54 in-field line breaks)','783,367 (day 1: 196,081; day 2: 587,286); 4 hosts'],
 ['Label','Creators’ ground truth: Normal 1,611,619; EoRS (Exploitation of Remote Services) 110,710; EoHT (Exploitation of Hashing Techniques) 30,507. Binary target = EoRS ∪ EoHT = 141,217 (8.06%); sub-type kept for Milestone 3 (Fig. 1).',`No per-event ground truth is published. Weak label by process-provenance tracing (§3.1.1): ${MLB.attack_rows.toLocaleString()} attack rows (${(MLB.attack_rate*100).toFixed(2)}%).`],
 ['Label entropy H(Y)',`${ML.label_entropy_bits.toFixed(3)} bits`,`${MM.label_entropy_bits.toFixed(3)} bits`],
 ['Capture structure',`Benign: 22 calendar days (Oct 2022, Nov 2022, Nov–Dec 2023; 21 benign-only) at ≈86,400 events/day on full days, i.e. one event per second. Attack: 2023-12-06 19:33 → 2023-12-08 10:47. The classes overlap for ${ST.lmd_overlap.seconds} s only (${ST.lmd_overlap.benign_after_first_attack} benign rows after the first attack row, ${ST.lmd_overlap.attack_before_last_benign} attack rows before the last benign row), so no chronological cut yields a two-class test set (Table 8; Fig. 2).`,`Two windows of ≈${Math.round(ST.mordor_sessions[0].minutes)} and ${Math.round(ST.mordor_sessions[1].minutes)} min, both on 2020-05-02 UTC (emulation days 1 and 2: ${ST.mordor_sessions[0].start}–${ST.mordor_sessions[0].end} and ${ST.mordor_sessions[1].start}–${ST.mordor_sessions[1].end}), both containing attack rows; background and attack events interleave in ${RT.mordor_bins.bins_both} of ${RT.mordor_bins.bins_total} five-minute bins (Fig. 2).`],
 ['Consequence','Absolute time is a label proxy (§3.3.1); no usable chronological split; within-LMD separability is capture structure (§4).','Temporally valid for windowed features; labels weak and partly circular with the lineage features (§3.1.1).'],
];
const t4=[headerRow(['','LMD-2023','Mordor APT29'],W4)];
T4.forEach((r,i)=>t4.push(drow(r,W4,i,{size:15,boldCol0:true})));
C.push(table(W4,t4)); C.push(tcap(4,'Dataset facts, labels and capture structure (all counts computed from the files).'));
C.push(h3('3.1.1 Mordor weak labels — exact procedure and limits'));
C.push(p([t(`(i) Seeds: Sysmon EID 1 processes whose image basename is in a fixed list of tools known from the emulation (psexec/psexec64/paexec, sdclt, m.exe, mimikatz, rar, python, mshta, wsmprovhost, seaduke), or whose command line contains encoded/hidden/download/remote-execution tokens or emulation-specific artefact names, or that are an interpreter spawned by sdclt/psexesvc/wmiprvse/wsmprovhost — ${MLB.seed_processes} processes. (ii) Propagation through the ProcessGuid→ParentProcessGuid tree to every descendant (fixpoint: ${MLB.malicious_processes} processes). (iii) Event labels: any event whose ProcessGuid or SourceProcessGUID is in the malicious lineage — and nothing else; no authentication-event rule is used, so Security-log features are not label-defining. Everything else is background, so the labels’ recall is unknown; Security-channel rows carry no ProcessGuid and are therefore always background, so the authentication/service family cannot be evaluated against these labels (§3.3). All ${MLB.hosts_with_malicious} hosts carry malicious processes. `),t('Circularity: ',{bold:true}),t('the seeds are read from Image, ParentImage and CommandLine of EID 1 events, so every feature computed from those fields (the whole lineage and command-line families) shares its inputs with the labelling rule; their scores against these labels are not validation, and Table 8 repeats the Mordor ranking without those families (and integrity_high, which belongs to them). Mordor scores are consistency checks of weak labels, never detection performance.')]));

C.push(h2('3.2 Noise and Redundancy Reduction'));
C.push(p([t('Criteria: zero variance, redundancy (|Spearman ρ| ≥ 0.7 with a stronger sibling, computed on a 300,000-row random sample; Fig. 4) and negligible class information on both datasets. Spearman rather than Pearson because most features are binary or heavy-tailed.')]));
C.push(p([t('Redundant pairs found (LMD, |ρ| ≥ 0.7): ',{bold:true}),t(RT.redundancy.map(r=>`${r[0]} ↔ ${r[1]} (ρ = ${r[2]})`).join('; ')),t('. Actions: the five time features are audit-only (§3.3.1); keep cmdline_entropy and drop cmdline_len (the cmdline features correlate with integrity_high only because all three are defined on EID 1 rows); keep both admin-port rates and inbound_peers although they correlate (all admin-port connections, the inbound subset, and distinct inbound peers — in LMD '+(100*AD.lmd_broadcast.admin_port.unicast_inbound_on_admin_port_share.attack).toFixed(0)+'% of unicast inbound attack connections but '+(100*AD.lmd_broadcast.admin_port.unicast_inbound_on_admin_port_share.benign).toFixed(0)+'% of benign ones target an admin port), because a model on another environment needs the three separately.')]));
C.push(p([t(`Zero-variance features are dataset-specific: ${RT.zero_variance.LMD.join(', ')} in LMD (no Security channel collected); ${RT.zero_variance.Mordor.join(', ')} in Mordor (one-day capture). They stay in the pool as the modality facts §5.2 handles.`),t(` Removing the five time features, cmdline_len and the control (${RT.n_pool} − 7) leaves the `),t(`${RT.n_unified}-column unified schema`,{bold:true}),t(` of §5.1 with no loss of non-artefact class information (the removed weekday and control carry ${ST.lmd_weekday_mi.toFixed(3)} and ${ST.lmd_pid_mi.toFixed(3)} bits in LMD, both capture artefacts; §3.3.1, §4.2).`)]));

C.push(h2('3.3 Empirical Justification Report'));
C.push(p([t('Analysis unit and inference. ',{bold:true}),t('One event row; every statistic below uses '),t('all',{italics:true}),t(' rows of each dataset. Effect sizes are the evidence: attack-positive AUC (0.5 = no separation; below 0.5 means attack rows have '),t('smaller',{italics:true}),t(' values), Cliff’s δ = 2·AUC − 1 for continuous features, Cramér’s V for binary/categorical ones, and mutual information in bits (plug-in estimator, continuous features quantile-binned into ≤ 32 bins) with an automated check 0 ≤ MI ≤ H(Y) on every feature (largest MI: LMD '),t(`${ST.lmd_max_mi.toFixed(3)} of ${ST.lmd_HY.toFixed(3)} bits; Mordor ${MM.max_mi_bits.toFixed(3)} of ${MM.label_entropy_bits.toFixed(3)}`),t(`). p-values (Mann–Whitney U; χ² or Fisher’s exact for sparse 2×2 tables; Holm-corrected over ${RT.n_pool} features) are anti-conservative because adjacent rows are autocorrelated, and are reported for completeness only.`)]));
const W6=[2250,1200,1200,1150,1250,1050,1260];
const t6=[headerRow(['Feature (LMD-2023)','Benign mean','Attack mean','AUC (attack+)','Effect size','MI (bits)','p (Holm)'],W6)];
RT.lmd_stats.forEach((r,i)=>t6.push(drow(r,W6,i,{size:15,boldCol0:true,centerFrom:1})));
C.push(table(W6,t6)); C.push(tcap(5,'Class-divergence evidence, LMD-2023, top 10 non-constant features by MI (complete pool: Fig. 10; n = 1,752,836, all rows). Means and AUC are not shown for nominal/cyclic codes (event category, weekday); Cramér\u2019s V applies.'));
C.push(p([t('Reading LMD. ',{bold:true}),t(`The trailing-window and graph features carry the most information (out-degree MI ${ST.lmd_read.outdeg_mi.toFixed(2)}, distinct dst-IPs ${ST.lmd_read.dstip_mi.toFixed(2)}), but on the source side their `),t('direction',{bold:true}),t(` is the opposite of the naive expectation: attack rows have lower outbound fan-out and network rate than benign rows (AUC ${Math.min(...ST.lmd_read.low_auc).toFixed(2)}–${Math.max(...ST.lmd_read.low_auc).toFixed(2)}), while the destination-side features — distinct inbound unicast peers (AUC ${ST.lmd_read.peers_auc.toFixed(2)}) and inbound admin-port connections (AUC ${ST.lmd_read.inbound_auc.toFixed(2)}) — and the process-creation rate (AUC ${ST.lmd_read.proc_auc.toFixed(2)}) are higher. The cause is capture structure: benign LMD is a one-event-per-second stream of outbound connections, ${(100*(AK.LMD.outbound_dest.benign.broadcast+(AK.LMD.outbound_dest.benign.multicast||0))).toFixed(0)}% of them broadcast or multicast and its inbound rows ${(100*(AK.LMD.inbound_src.benign.broadcast||0)).toFixed(0)}% broadcast, whereas attack rows are ${(100*AK.LMD.outbound_dest.attack.unicast).toFixed(0)}% unicast outbound and ${(100*AK.LMD.inbound_src.attack.unicast).toFixed(0)}% unicast inbound — a dense host-event burst with few, targeted connections and genuine inbound peers (hence the unicast-only rule of §1.3; the chatter still drives the connection rate). Table 5 shows two capture regimes, not that low fan-out characterises lateral movement. The finding that survives the within-LMD modality control is the inbound admin-port burst on the destination host (Fig. 3; within network rows attack `),t(f2(CF.f_inbound_adminport_60s.net_attack_mean)),t(' vs benign '),t(f2(CF.f_inbound_adminport_60s.net_benign_mean)),t(' per minute, AUC '),t(f3(CF.f_inbound_adminport_60s.net_auc_attack_pos)),t(`); on Mordor’s weak labels the same feature is near chance (AUC ${ST.mordor_inbound_auc.toFixed(2)}), so it is not yet a cross-environment result. Its composition matters for transfer: ${(100*AD.lmd_broadcast.admin_port.attack_share_ldap_kerberos).toFixed(0)}% of the attack-row inbound admin-port connections are LDAP/Kerberos (389, 88, 464) to the domain controller — directory enumeration and ticket traffic of the attacking hosts — and ${(100*AD.lmd_broadcast.admin_port.attack_share_remote_service_ports).toFixed(0)}% RPC/SMB/WinRM/RDP (135, 445, 5985, 3389), while benign inbound admin-port rows are almost all SMB (445); a production domain controller receives LDAP/Kerberos constantly, so the burst is a rate signal against the host’s own baseline, not a port signature.`)]));
const t7=[headerRow(['Feature (Mordor APT29)','Benign mean','Attack mean','AUC (attack+)','Effect size','MI (bits)','p (Holm)'],W6)];
RT.mordor_stats.forEach((r,i)=>t7.push(drow(r,W6,i,{size:15,boldCol0:true,centerFrom:1})));
C.push(table(W6,t7)); C.push(tcap(6,'Class-divergence evidence, Mordor APT29, top 8 by MI (complete pool: Fig. 11) plus the Security-log authentication/service family (n = 783,367, all rows; weak labels).'));
C.push(p([t('Reading Mordor. ',{bold:true}),t(`image_is_lolbin dominates (V = ${ST.mordor_lolbin_V.toFixed(2)}) but shares its input field with the label seeds (§3.1.1). Outside the seed-field families, the signals are the same out-degree/fan-out family (AUC ${Math.min(...ST.mordor_fanout_auc).toFixed(2)}–${Math.max(...ST.mordor_fanout_auc).toFixed(2)}; attack lower again) and event category (V = ${SM_EC_V}; Fig. 11). The Security-log features cannot carry class information under these labels by construction (V ≤ ${ST.mordor_auth_V_max.toFixed(3)}, §3.1.1) — a label-design limit, not evidence that authentication telemetry lacks value; testing that plane needs independent per-session annotation, so the family is kept on domain grounds and marked † in Table 9.`)]));
C.push(h3('3.3.1 Symmetric scepticism toward temporal features'));
C.push(p([t(`Weekday and seconds-in-day are judged by the same standard. In LMD, weekday carries ${ST.lmd_weekday_mi.toFixed(3)} bits (V = ${ST.lmd_weekday_V.toFixed(2)}) — more than any single-event network flag — purely because attacks occupy three calendar days, while seconds-in-day is weak (MI ${ST.lmd_secday_mi.toFixed(3)}) because the attack ran round the clock. In Mordor, weekday is constant (MI = ${ST.mordor_weekday_mi}) and seconds-in-day is strong (MI ${ST.mordor_secday_mi.toFixed(3)}) because the capture is two windows of ≈${Math.round(ST.mordor_sessions[0].minutes)} and ${Math.round(ST.mordor_sessions[1].minutes)} minutes whose attack densities differ by an order of magnitude (${ST.mordor_sessions[0].attack_pct.toFixed(1)}% and ${ST.mordor_sessions[1].attack_pct.toFixed(1)}% of rows), so time-of-day identifies the window. Neither is adversary behaviour; both are capture schedules (Fig. 2), so all five time features are excluded from the prospective model schema — a real adversary can pivot during business hours.`)]));

// ===================== CHAPTER 4 =====================
C.push(h1('Chapter 4 — Algorithmic Feature Ranking and Verification (Step 4)'));
C.push(h2('4.1 Tree-Based Feature Importance Ranking'));
C.push(p([t('Set-up. ',{bold:true}),t(`The full ${RT.n_pool}-feature pool is ranked on each dataset independently by a Random Forest (300 trees, max_depth 8, min_samples_leaf 50, √d features per split, class_weight = balanced_subsample) and a LightGBM model (300 trees, max_depth 8, 31 leaves, learning rate 0.05, min_child_samples 50, balanced class weights) on a 400,000-row sample per dataset drawn as: every positive row kept, negatives sampled uniformly (seed 42); permutation importance is the mean held-out AUC drop over 5 permutations. Positive rates are therefore higher than in the full data — LMD ${(SP.LMD.random.prev_test*100).toFixed(1)}% (vs ${(ML.attack_prevalence*100).toFixed(2)}%), Mordor ${(SP.Mordor.random.prev_test*100).toFixed(1)}% (vs ${(MLB.attack_rate*100).toFixed(2)}%) — and are printed next to every PR-AUC, whose chance level equals the prevalence. Because Gini/MDI favours high-cardinality features, MDI, permutation importance (held-out AUC drop) and LightGBM gain are reported side by side (Figs. 6–7, Table 7). Depth and leaf limits curb memorisation of continuous values; they do not address split leakage, which Table 8 audits.`)]));
const W8=[1900,620,820,700,1900,620,820,700];
const t8=[headerRow(['LMD-2023 feature','RF MDI','RF perm. ΔAUC','LGBM gain','Mordor APT29 feature','RF MDI','RF perm. ΔAUC','LGBM gain'],W8)];
RT.rank_lmd.forEach((r,i)=>t8.push(drow([...r,...RT.rank_mordor[i]],W8,i,{size:15,centerFrom:1,leftCols:[4]})));
C.push(table(W8,t8)); C.push(tcap(7,'Top-10 features by composite importance (mean of normalised RF MDI and LightGBM gain) on LMD-2023 (left) and Mordor APT29 (right, weak labels); RF permutation ΔAUC alongside.'));
C.push(h3('Split and leakage audit'));
C.push(p([t('Rolling and graph features are causal, but adjacent rows share most of their window history, so an event-level random split overstates generalisation, and even a host × 10-minute grouping leaves the one-hour out-degree window straddling block boundaries. Table 8 repeats the RF evaluation '),t('without any absolute-time feature',{italics:true}),t(' under four splits of the same 400k-row sample (exact row and positive counts; sensitivity checks, not deployment estimates; the full-data statistics of §3 are unaffected), and its ‡ rows repeat the Mordor grouped splits without the seed-field families of §3.1.1.')]));
const W10=[1050,1800,950,950,950,950,900,910,900];
const t10=[headerRow(['Dataset','Split (grouping key)','n train','pos train','n test','pos test','test prev.','ROC-AUC','PR-AUC'],W10)];
let k=0;
for(const ds of ['LMD','Mordor']) for(const [nm,lab] of [['random','random, stratified'],['grouped_host10min','host × 10-min block'],['grouped_host_day','host × day'],['chronological_70_30','chronological 70/30']]){
  const r=SP[ds][nm]; t10.push(drow([ds,lab,r.n_train.toLocaleString(),r.pos_train.toLocaleString(),r.n_test.toLocaleString(),r.pos_test.toLocaleString(),(r.prev_test*100).toFixed(1)+'%', r.auc==null?'n/a*':f4(r.auc), r.auc==null?'n/a*':f4(r.prauc)],W10,k++,{size:15,centerFrom:2}));}
const RD=SP['Mordor'];
[['grouped_host10min','host × 10-min block'],['grouped_host_day','host × day']].forEach(([k2,lab])=>{const r=RD[k2+'_reduced'];
  t10.push(drow([`Mordor ‡ (${r.n_features} features)`,lab,r.n_train.toLocaleString(),r.pos_train.toLocaleString(),r.n_test.toLocaleString(),r.pos_test.toLocaleString(),(r.prev_test*100).toFixed(1)+'%',f4(r.auc),f4(r.prauc)],W10,k++,{size:15,centerFrom:2}));});
C.push(table(W10,t10)); C.push(tcap(8,`Split audit (Random Forest, ${SP.LMD.random.n_features} features: the pool without the five time features; sample as described in §4.1). Mordor spans one day, so its host × day split is a leave-hosts-out split (4 groups). ‡ Reduced-feature consistency check: the ${RD.grouped_host10min_reduced.n_features} features left after also removing the lineage and command-line families (every feature that reads Image, ParentImage or CommandLine, plus integrity_high) and the PID control — a check against weak labels, not validated detection. *LMD chronological split: the last 30% of the timeline contains only attack rows, so ROC-AUC is undefined and average precision is not reported (trivially 1.0 on an all-positive set) — direct evidence of the temporal separation of the classes.`));
C.push(p([t('Result. ',{bold:true}),t('LMD stays at AUC ≈ 1.0 under every feasible split, including host × day grouping (0.998), because attack and benign rows differ structurally in event-type composition, cadence and network density (Figs. 2, 5) — a property of the capture, not detection performance. Mordor falls from '),t(f4(RD.random.auc)),t(' (random) to '),t(`${f4(Math.min(RD.grouped_host_day.auc,RD.grouped_host10min.auc,RD.chronological_70_30.auc))}–${f4(Math.max(RD.grouped_host_day.auc,RD.grouped_host10min.auc,RD.chronological_70_30.auc))}`),t(' under grouped or chronological splits, and to '),t(`${f4(RD.grouped_host10min_reduced.auc)} ROC-AUC / ${f4(RD.grouped_host10min_reduced.prauc)} PR-AUC`,{bold:true}),t(` (host × 10-min) and ${f4(RD.grouped_host_day_reduced.auc)} / ${f4(RD.grouped_host_day_reduced.prauc)} (host × day, i.e. leave-hosts-out — chance level) once the lineage and command-line families — every feature that reads a seed field — are removed (Table 8, ‡ rows): a consistency check`),t(' between the remaining telemetry and weak labels of unknown recall, not validated detection; PR-AUC differences across splits also reflect their test prevalences.')]));

C.push(h2('4.2 Critical Discrepancy Analysis'));
C.push(p([t('Alignment. ',{bold:true}),t(`The rankings agree with Chapter 1 in kind: out-degree, the inbound-peer count and the fan-out/rate aggregates top LMD, with event category and the destination-side inbound admin-port rate inside the top ten; event category, out-degree, fan-out and net-conns top Mordor once image_is_lolbin and the time features are set aside. Single-event raw flags (initiated, admin_port_flag, is_ipv6) rank ${ord(RK.flags_LMD[0])}–${ord(RK.flags_LMD[1])} in LMD and ${ord(RK.flags_Mordor[0])}–${ord(RK.flags_Mordor[1])} in Mordor, below the out-degree, fan-out and host-event-rate aggregates on both, as expected. Cross-dataset agreement of importances on the composite basis of Table 7 (average ranks for ties) is moderate (Spearman ρ = `),t(f2(S.cross_rank_spearman)),t(`; Fig. 9). The largest rank gaps (LMD vs Mordor) are ${RT.cross.slice(0,5).map(r=>`${r[0]} (${r[1]} vs ${r[2]})`).join(', ')} — the environment-specific features.`)]));
C.push(p([t(`Surprise 1 — weekday ranks ${ord(RK.weekday_LMD)} in LMD and joint last (zero importance) in Mordor (leakage). `,{bold:true}),t(`It is the only LMD feature with a material permutation drop (${ST.lmd_perm_top[1].toFixed(4)}; every other feature < 0.0002) and it has zero importance in Mordor, because it identifies the three LMD attack days (Fig. 2, Table 8); excluded with the other time features.`)]));
C.push(p([t('Surprise 2 — the previous “relational PID” feature is a null-fill artefact. ',{bold:true}),t(`naive_relational_pid = [ProcessId = ExecutionProcessID] compares the EventData subject PID with the header PID of the logging process. The LMD export writes “0” into empty fields; on EID 10 (ProcessAccess) rows both are empty, so equality holds for 100.0% of EID 10 rows (97.7% of all rows on which the feature fires), for at most 0.22% of any other event type with more than 500 rows, and otherwise on 654 rare housekeeping rows (EID 4/16/8/6/255). Its attack mean (${ST.lmd_pid_attack_mean.toFixed(3)}) equals the EID 10 share of attack rows (${ST.lmd_attack_eid10_pct.toFixed(1)}%): an event-type indicator created by the export convention, not lineage; it ranks ${ord(RK.pid_LMD)} on LMD and has zero importance on Mordor, where empty fields are genuinely null.`)]));
C.push(p([t('Surprise 3 — near-perfect fan-out features (modality confound; capture-specific magnitude). ',{bold:true}),t(`Benign LMD is ${ST.lmd_benign_eid3_pct}% network events (EID 3); attack rows are ${ST.lmd_attack_eid_pct['7']}% image loads (EID 7), ${ST.lmd_attack_eid_pct['10']}% process access (EID 10), ${ST.lmd_attack_eid_pct['23']}% file deletes (EID 23) and ${ST.lmd_attack_eid_pct['3']}% network (Fig. 5). A host-event row carries its host’s trailing outbound fan-out, which is small in the attack period (host rows average ${f2(CF.f_distinct_dstip_300s.host_attack_mean)} distinct destinations in attack windows vs ${f2(CF.f_distinct_dstip_300s.host_benign_mean)} in benign ones), so part of the feature’s power is event-type composition. Within network rows only, distinct_dstip_300s still separates (attack ${f2(CF.f_distinct_dstip_300s.net_attack_mean)} vs benign ${f2(CF.f_distinct_dstip_300s.net_benign_mean)} distinct IPs; attack-positive AUC ${f3(CF.f_distinct_dstip_300s.net_auc_attack_pos)}), but far more weakly in Mordor (MI ${ST.mi_dstip.Mordor.toFixed(2)} vs ${ST.mi_dstip.LMD.toFixed(2)}): the LMD magnitude reflects its background-traffic density.`)]));
C.push(p([t('Surprise 4 — host/credential features rank low on LMD (modality sparsity). ',{bold:true}),t(`Features that need ParentImage/CommandLine (EID 1), GrantedAccess (EID 10) or TargetFilename (EID 11) are defined on under ${Math.ceil(ST.lmd_eid1_10_11_pct)}% of LMD rows, so on an unpartitioned matrix they win little global impurity reduction whatever their within-modality value (only image_is_lolbin and exec_from_staging, which read Image on any event, reach more rows). The benign zeros of the credential features (lsass_access ${ST.lmd_lsass_attack_pct.toFixed(2)}% of attack rows) are composition, not specificity: benign LMD holds ${ST.lmd_benign_eid10_rows===1?'a single EID 10 row':ST.lmd_benign_eid10_rows+' EID 10 rows'}, so cred_access_mask’s V = ${ST.lmd_credmask_V.toFixed(2)} (Fig. 10) is the Surprise-3 confound again. The remedy is modality-aware evaluation and per-host aggregates defined on every row (§5), not discarding them.`)]));
C.push(p([t('Multicollinearity and saturation. ',{bold:true}),t('Permutation drops are ≈ 0 for almost every LMD feature because redundant siblings (§3.2) absorb a permuted column and a saturated AUC is insensitive to small changes — hence three importance measures and one composite basis.')]));

// ===================== CHAPTER 5 =====================
C.push(h1('Chapter 5 — Multi-Dataset Sourcing and Harmonization (Step 5)'));
C.push(h2('5.1 Unified Feature Schema'));
C.push(p([t(`One parser per source produces a common intermediate event schema and one shared function engineers every feature, so definitions are identical by construction. The unified schema is the candidate pool minus the five time features, cmdline_len and the control: ${RT.n_pool} − 7 = ${RT.n_unified} columns (Table 9, generated from the code’s feature registry), of which event_category expands to one-hot indicators for distance-based models: ${RT.n_event_categories} levels are observed here (${RT.n_event_categories-1} semantic categories plus “other”), and the Milestone-3 code allocates all ${RT.n_registry_levels} registry levels so that an unseen category keeps its slot, giving D = ${RT.n_unified} − 1 + ${RT.n_registry_levels} = ${RT.D_lstm_registry} for the LSTM (§6.1).`)]));
const UW=RT.unvalidated_why; const fx=(f)=>UW['f_'+f]; const lift=(f,ds)=>fx(f)[ds].lift.toFixed(1); const af=(f,ds)=>fx(f)[ds].attack_fires;
C.push(p([t(`Of the ${RT.n_unified} columns, ${RT.n_unified-RT.n_unvalidated} carry statistical support in at least one dataset under the Table 9 criterion — class association, not causation: the fan-out family’s LMD evidence is the two-regime effect of §3.3 and the credential family’s the composition effect of §4.2 (complete evidence in Figs. 10–11). The remaining ${RT.n_unvalidated} († in Table 9) fail it in both datasets for reasons that differ by feature: the ${RT.unvalidated_by_family.auth_service.length} Security-auditing flags are constant in LMD (no Security channel) and cannot be positive under Mordor’s provenance labels (§3.1.1); the ${RT.unvalidated_by_family.modality.length} modality indicators are context by design; lolbin_parent_child and cmdline_susp fire ${lift('lolbin_parent_child','LMD')}× and ${lift('cmdline_susp','LMD')}× as often in LMD attack rows as in benign rows but on only ${af('lolbin_parent_child','LMD')} and ${af('cmdline_susp','LMD')} attack rows (sparse); rare_dst_pair (lift ${lift('rare_dst_pair','LMD')}) and cmdline_entropy (Cliff’s δ = ${fx('cmdline_entropy').LMD.effect.toFixed(2)}, computed over all rows, most of which carry no command line) are Holm-significant in LMD but below the effect threshold; file_drop_staging is rarer in LMD attack rows than in benign rows and fires ${lift('file_drop_staging','Mordor')}× as often in Mordor attack rows (below the ×3 bar); lsass_access fires on ${af('lsass_access','LMD')} LMD attack rows and ${fx('lsass_access').LMD.benign_fires} benign rows — unscorable by lift and composition rather than specificity, since benign LMD holds a single EID 10 row (§4.2) — and is commoner in benign than in attack rows of Mordor. They remain domain-grounded candidates, not validated inputs, to be tested in Milestone 3 on independently annotated sessions.`)]));
const W12=[1250,2900,1500,1500,1000,1210];
const t12=[headerRow(['Family','Unified features († = below the criterion in both datasets)','LMD origin','Mordor origin','Scaling','Statistical evidence'],W12)];
const UNV=new Set(RT.unvalidated.map(x=>x.slice(2)));
RT.schema_rows.forEach((r,i)=>{const rr=r.slice(); rr[1]=rr[1].split(',').map(x=>x.trim()).map(x=>UNV.has(x)?x+'†':x).join(', '); t12.push(drow(rr,W12,i,{size:15,boldCol0:true}));});
C.push(table(W12,t12)); C.push(tcap(9,`Unified feature schema (${RT.n_unified} columns, ${RT.schema_rows.length} families; generated from the code). Robust = median/IQR, fit on the training fold only; absent Security-log telemetry is 0 with sec_observed = 0. Evidence = at least one feature of the family is Holm-significant (p < .05) in that dataset and either |effect| ≥ 0.1 or, for a Cramér’s-V feature, lift ≥ 3 on ≥ 100 attack-row fires with a non-zero benign rate, where lift = mean(flag | attack) / mean(flag | benign); † marks the ${RT.n_unvalidated} columns below it in both datasets (§5.1); the modality indicators are context, not detectors.`));
C.push(h2('5.2 Cross-Dataset Distribution Shift'));
C.push(p([t('Fig. 8 compares features across datasets; three shifts are structural. (1) '),t('Telemetry-modality inversion: ',{bold:true}),t(`LMD is network-centric (EID 3 ≈ ${RT.lmd_eid3_pct}% of rows; initiated fires on ${RT.lmd_initiated_pct}%), Mordor host-centric (EID 3 ≈ ${RT.mordor_eid3_pct}%; initiated ${RT.mordor_initiated_pct}%), and only Mordor carries the Security channel, so the auth/service family is all-zero in LMD: a model keyed on socket features meets the network plane in only ${RT.mordor_eid3_pct}% of Mordor’s events and is expected to degrade there (measured in Milestone 3), and one keyed on 4624/4648 has constant inputs on LMD. (2) `),t('Temporal shift: ',{bold:true}),t('diurnal_sin spans the day in LMD and collapses to two narrow spikes in Mordor. (3) '),t('Scale shift: ',{bold:true}),t(`the all-rows median of host_evt_rate_60s is ${SS.LMD.f_host_evt_rate_60s.median.toLocaleString()} in LMD and ${SS.Mordor.f_host_evt_rate_60s.median.toLocaleString()} in Mordor (90th percentiles ${SS.LMD.f_host_evt_rate_60s.p90.toLocaleString()} vs ${SS.Mordor.f_host_evt_rate_60s.p90.toLocaleString()}). Table 10 states each remedy and its status.`)]));
const W13=[3100,1500,4760];
const T13=[
 ['Host + network feature families in one schema','implemented','Evidence from both planes in one model; whether one modality dominates is what the indicators below and the cross-dataset evaluation measure.'],
 ['Observed-modality indicators','implemented (causal)',`sec_observed = 1 from the host’s first authentication/service event (4624, 4648, 4688, 4769, 5140, 5145, 7045, 4697) onward, net_observed = 1 from its first EID 3 (running maxima): with the indicator at 1 a zero-valued flag is a recorded zero, before the first qualifying event it is “not yet observed”. On the feature matrix that window holds ${ADM.rows_sec_zero_total.toLocaleString()} Mordor rows (${ADM.pct_sec_zero}%; ≈ ${Math.round(ADM.max_seconds_sec_zero/60)} min on one host; no attack rows) for sec_observed and ${ADM.rows_net_zero_total.toLocaleString()} (${ADM.pct_net_zero}%; ≤ ${Math.round(ADM.max_seconds_net_zero)} s) for net_observed; LMD has no Security channel, so its sec_observed = 0 is “not collected” by construction.`],
 ['Robust scaling fit on the training fold','implemented (scaling_audit.py); model use in Milestone 3','Median/IQR per continuous feature fitted on training rows only and applied unchanged to held-out rows (§5.3); the same rule governs Milestone-3 class weighting or resampling.'],
 ['Quantile alignment','specified; Milestone 3','Within-dataset percentiles of the continuous features before transfer (so “top-5% fan-out for this environment” is the transferable quantity).'],
 ['Per-(host, 60 s) records; cross-host stitching','specified; outside the Milestone-3 scope','A per-host-window analysis unit; outbound/inbound events joined by (SourceIp, DestinationIp, time). Milestone 3 keeps the per-event unit so that decisions stay comparable across the four models.'],
 ['Cross-dataset evaluation','specified; Milestone 3','Train-on-LMD/test-on-Mordor and the reverse, with within-Mordor grouped splits; a large drop is diagnosed as environment overfitting.'],
];
const t13=[headerRow(['Remedy','Status','Definition'],W13)];
T13.forEach((r,i)=>t13.push(drow(r,W13,i,{size:15,boldCol0:true})));
C.push(table(W13,t13)); C.push(tcap(10,'Engineering remedies for dataset-specific bias, with implementation status.'));
C.push(h2('5.3 Data Scaling and Scaling Remedies'));
C.push(p([t('Continuous rate, fan-out, out-degree and Δt features are right-skewed with burst outliers, so RobustScaler x′ = (x − median)/IQR is used (IQR = 0 → divisor 1): Z-scores are dominated by the outliers and min-max compresses the bulk. Binary flags stay in {0, 1}; event_category is one-hot for distance-based models; the Chapter-4 trees used its integer code, whose arbitrary order can change which splits are found and hence the MDI/gain credited to the column (a caveat on its Table 7 ranks; its class association rests on the order-free Cramér’s V of Table 5 and Figs. 10–11). Protocol: split → fit the scaler on training rows → transform every other set with those medians and IQRs; Milestone-3 imbalance handling (class weights, or any resampler) obeys the same rule. '),t(`Audit (scaling_audit.py, host × day split, ${RT.scaling.continuous_features.length} continuous features): host_evt_rate_60s has training median/IQR ${RT.scaling.LMD.features.f_host_evt_rate_60s.train_median.toLocaleString()}/${RT.scaling.LMD.features.f_host_evt_rate_60s.train_iqr.toLocaleString()} in LMD and ${RT.scaling.Mordor.features.f_host_evt_rate_60s.train_median.toLocaleString()}/${RT.scaling.Mordor.features.f_host_evt_rate_60s.train_iqr.toLocaleString()} in Mordor; and the LMD-fitted transform puts Mordor’s median at ${RT.scaling.cross_fit.f_host_evt_rate_60s.mordor_median_under_LMD_fit.toLocaleString(undefined,{maximumFractionDigits:0})} scaled units — a source-fitted scaler alone does not remove the scale shift; `),t('quantile alignment (Table 10) is the additional step.')]));

// ===================== CHAPTER 6 =====================
C.push(h1('Chapter 6 — Model Selection and Academic Grounding (Step 6)'));
C.push(h2('6.1 Architectural Customization Justification'));
C.push(p([t('Table 11 gives the four architectures — the three required paradigms plus a sequence model — with their mathematical basis and fit to the threat and the schema.')]));
const W14=[1350,1400,3300,3310];
const T14=[
 ['Random Forest','Supervised, bagging','ŷ = mode{hᵢ(x)}, i = 1…B; the B trees are grown on bootstrap samples with √d features per split.','Non-linear interactions across mixed families, robust to residual redundancy, no scaling; continuity with the Chapter-4 ranking.'],
 ['LightGBM','Supervised, boosting','Fₙ(x) = Fₙ₋₁(x) + η·hₙ(x); leaf-wise growth on histogram splits.','Primary classifier: learns conjunctions such as inbound-admin-port ∧ remote-exec lineage ∧ velocity; class weights handle 8%/4% prevalence at 10⁶ rows.'],
 ['LSTM','Deep, sequential','cₜ = fₜ⊙cₜ₋₁ + iₜ⊙c̃ₜ with input/forget/output gates over an ordered sequence.','Lateral movement is a multi-stage sequence (logon → remote-exec → tool drop → credential access); recurrence models the order — only with sequence framing (below).'],
 ['Isolation Forest','Unsupervised, anomaly','s(x, n) = 2^(−E[h(x)]/c(n)); anomalies isolate in short random paths.','Label-free first-line filter for unseen tradecraft; natural where labels are weak (Mordor).'],
];
const t14=[headerRow(['Model','Paradigm','Mathematical basis','Fit to threat and features'],W14)];
T14.forEach((r,i)=>t14.push(drow(r,W14,i,{size:15,boldCol0:true})));
C.push(table(W14,t14)); C.push(tcap(11,'Four selected models across the three required paradigms.'));
C.push(p([t('LSTM sequence framing. ',{bold:true}),t(`An LSTM needs a tensor of shape (batch, T, D). Events are ordered by timestamp per host; a window is the T = 20 events of the host ending at a given event (windows end at every 4th event in LMD and every 2nd in Mordor, for cost), and a shorter history is pre-padded with unmasked zero vectors. Each timestep is the ${RT.n_unified}-column schema with event_category one-hot over the registry’s ${RT.n_registry_levels} levels (${RT.n_event_categories} of them observed here; ${RT.n_unified} − 1 + ${RT.n_registry_levels} = ${RT.D_lstm_registry} inputs), scaled per §5.3; the window carries the label of its last event, giving a causal per-event decision comparable with the row-level models. Stacked LSTM (64 → 32 units), dropout 0.3, batch normalisation, class-weighted cross-entropy, Adam at 10⁻³, early stopping on a grouped inner hold-out (tuned in Milestone 3). The LSTM baselines in [2, 3] consume per-event vectors (T = 1), so their scores are not sequence-model benchmarks for this framing.`)]));
C.push(h2('6.2 State-of-the-Art Literature Synthesis'));
const W15=[2450,1350,2700,2860];
const T15=[
 ['Bai et al. 2021 [1] — LogitBoost; RF, LightGBM baselines','LANL RDP sessions (56,837) [6]','≈100 DT estimators, 10-fold CV; identity features removed for robustness','Acc 99.99%, Prec 99.87%, Rec 99.73%, F1 0.998; without identity fields F1 0.997; unseen-source AP 0.95'],
 ['Smiliotopoulos et al. 2023 [2] and Smiliotopoulos & Kambourakis 2026 [3] — RF, LightGBM, ExtraTrees, Bagging-LightGBM, LSTM','LMD-2023 (event-level)','[2]: 15 columns incl. 7 calendar fields, hand-set hyper-parameters without automated tuning, per-event LSTM on the 90-column one-hot vector. [3]: 8 PCA-selected fields, 16 resampling scenarios, scalers/resamplers fit on train folds','[2]: ExtraTrees best — AUC 99.84% / F1 99.41%; RF AUC 99.68%; LightGBM 99.61%; DT 99.53%; per-event LSTM AUC 95.82% / F1 95.55%. [3]: resampling adds ≈0.05 p.p. (shallow), ≈3.5 p.p. (DNN); Bagging near-zero FNR on some balanced sets'],
 ['Le & Zincir-Heywood 2021 [11] — Isolation Forest (unsupervised ensembles)','CERT r4.2/r6.2, LANL, TWOS (user-day / user-week records)','IF with 200 trees, max_samples 256; label-free training on a user subset over the first half of each dataset; results reported on the entire dataset, training period included (not strictly held-out)','IF instance-level AUC 0.825 / user-level 0.847 on CERT r4.2 (weekly, original features; their Table III); insider-threat task, not LM'],
 ['Smiliotopoulos et al. 2025 [4] — unsupervised (5 shallow, 4 deep)','LMD-2023','feature selection + tuning; two-stage pipeline','best shallow ≈94.7% AUC / 93% F1; best deep ≈95.2% / 93.8%; two-stage +≈3.5%'],
 ['Kushwaha et al. 2022 [5] — XGBoost, deep FCDN','LANL [6]','9 user-behavioural features incl. 60-s process-execution and time-since-logon windows','XGBoost recall 86.51% / FPR 0.0013%; FCDN recall 92.13% / FPR 0.0029%'],
];
const t15=[headerRow(['Study (model)','Dataset','Configuration','Reported results (authors’ figures)'],W15)];
T15.forEach((r,i)=>t15.push(drow(r,W15,i,{size:15})));
C.push(table(W15,t15)); C.push(tcap(12,'Literature grounding for the four architectures, checked against the primary sources. Results are the authors’, on their own targets, and are not comparable with Table 8; the hyper-parameters of [3] could not be re-verified from the full text.'));
C.push(p([t('Synthesis (Table 12). ',{bold:true}),t('Tree ensembles are the strongest, cheapest tabular baselines for Sysmon LM data [2, 3]; unsupervised detectors reach ≈95% AUC on LMD-2023 [4], and Isolation Forest is a common label-free baseline on user/host telemetry [11] (Table 12 notes its evaluation caveat); behavioural window features drive the LANL results [1, 5]. The supervised LMD-2023 benchmarks rest on capture identifiers — seven calendar fields in [2] (F1 99.41%), CompSTA and EventRecordID in [3] — and §3.3 and Table 8 show why such scores are a property of the capture; Milestone 3 therefore reports cross-dataset and within-Mordor grouped-split results beside the LMD figures and treats the gap as the finding.')]));

// ===================== REFERENCES =====================
C.push(h1('References'));
['T. Bai, H. Bian, M. A. Salahuddin, A. Abou Daya, N. Limam, R. Boutaba, “RDP-based Lateral Movement detection using Machine Learning,” Computer Communications, vol. 165, pp. 9–19, 2021. doi:10.1016/j.comcom.2020.10.013',
 'C. Smiliotopoulos, G. Kambourakis, K. Barbatsalou, “On the detection of lateral movement through supervised machine learning and an open-source tool to create turnkey datasets from Sysmon logs,” Int. J. Inf. Secur., vol. 22, no. 6, pp. 1893–1919, 2023. doi:10.1007/s10207-023-00725-8',
 'C. Smiliotopoulos, G. Kambourakis, “Machine Learning for Lateral Movement Detection using Sysmon Logs: An Empirical Comparison of Imbalanced and Resampled Data,” Int. J. Inf. Secur., vol. 25, no. 1, art. 38, 2026. doi:10.1007/s10207-025-01182-1',
 'C. Smiliotopoulos, G. Kambourakis, C. Kolias, S. Gritzalis, “Assessing the detection of lateral movement through unsupervised learning techniques,” Computers & Security, vol. 149, art. 104190, 2025.',
 'D. Kushwaha et al., “Lateral Movement Detection Using User Behavioral Analysis,” arXiv:2208.13524, 2022.',
 'A. D. Kent, “Comprehensive, Multi-Source Cyber-Security Events Data Set,” Los Alamos National Laboratory, 2015. doi:10.17021/1179829',
 'MITRE ATT&CK, Lateral Movement (TA0008); T1021, T1210, T1550, T1570. https://attack.mitre.org/tactics/TA0008/',
 'Open Threat Research Forge, Security-Datasets — APT29 adversary-emulation host datasets (day 1, day 2). https://github.com/OTRF/Security-Datasets',
 'C. Smiliotopoulos, LMD-2023 — Lateral-Movement-Dataset (LMD_Collections), GitHub, 2023.',
 'Microsoft, Sysmon event reference, https://learn.microsoft.com/sysinternals/downloads/sysmon; Windows security auditing event reference, https://learn.microsoft.com/windows/security/threat-protection/auditing/.',
 'D. C. Le, N. Zincir-Heywood, “Anomaly Detection for Insider Threats Using Unsupervised Ensembles,” IEEE Trans. Netw. Serv. Manag., vol. 18, no. 2, pp. 1152–1164, 2021. doi:10.1109/TNSM.2021.3071928',
].forEach((r,i)=>C.push(new Paragraph({spacing:{after:40,line:235},indent:{left:360,hanging:360},children:[t(`[${i+1}] `,{bold:true,size:17}),t(r,{size:17})]})));

// ===================== APPENDIX A: REPRODUCIBILITY =====================
C.push(h1('Appendix A — Reproducibility and feature registry'));
C.push(p([t('Package. ',{bold:true}),t(`Twelve scripts (extraction, features, statistics, ranking, split and scaling audits, confound diagnostics, data checks, figures, table export, report generator), artifacts/ (every statistic for the ${RT.n_pool} features on both datasets, every table row and every derived number; the dataset facts of Table 4, the EID-composition percentages of §4.2, the paper facts and the model settings are typed from their sources), figures/ and a README (run order, environment). `),t('Feature registry (common_features.FEATURE_COLS). ',{bold:true}),t(`Prospective schema: the ${RT.n_unified} columns of Table 9 (${RT.n_unvalidated} marked †); audit-only / excluded (7, §3.2); event_category: ${RT.n_event_categories} observed one-hot levels (D_lstm ${RT.D_lstm} in report_tables.json) vs ${RT.n_registry_levels} registry levels in Milestone 3 (D ${RT.D_lstm_registry}). 10 pt body text at 1.5 line spacing; text pages 1–16 (cover included), figures (Appendix B) from page 17.`)],{line:300,after:70}));

C.push(h1('Appendix B — Figures',true));
C.push(p('Supporting exploration graphs referenced in Chapters 3–5; generated by figures.py from the artifact tables. Figures 10–11 give the complete candidate-pool evidence behind Tables 5–6.',{after:60}));
C.push(...figure('fig01_class_dist.png',1,'Class distribution in both datasets (log scale). LMD-2023 keeps its EoRS/EoHT taxonomy; Mordor is binary with weak labels.',540));
C.push(...figure('fig02_timeline.png',2,`Capture structure. Left: LMD-2023 events per calendar day — benign days run at 86,400 events/day (one per second) and attack rows occupy 6–8 Dec 2023 only. Right: Mordor events per 5-minute bin — classes interleave in ${RT.mordor_bins.bins_both} of ${RT.mordor_bins.bins_total} bins.`,624));
C.push(...figure('fig03_boxplots.png',3,'Class-conditional distributions (LMD-2023, 99th-percentile clipped): attack rows show lower out-degree and fan-out but far more inbound admin-port connections and process creations.',600));
C.push(new Paragraph({children:[new PageBreak()]}));
C.push(...figure('fig04_corr.png',4,'Spearman correlation matrix of the non-constant candidate features (LMD-2023, 300,000-row sample). Warm = positive, cool = negative.',624));
C.push(...figure('fig05_modality.png',5,'Event-ID composition of benign vs attack rows in LMD-2023 — the modality confound behind Surprise 3.',500));
C.push(new Paragraph({children:[new PageBreak()]}));
C.push(...figure('fig06_imp_lmd.png',6,'LMD-2023 feature importance (top 16): RF MDI, LightGBM gain and RF permutation (scaled). Permutation drops are ≈ 0 for all but weekday because held-out AUC is saturated at 1.0 and redundant siblings compensate.',520));
C.push(...figure('fig07_imp_mordor.png',7,'Mordor APT29 feature importance (top 16, weak labels). image_is_lolbin is partly a label-construction effect (§3.1.1).',520));
C.push(new Paragraph({children:[new PageBreak()]}));
C.push(...figure('fig08_shift.png',8,'Cross-dataset distribution shift of candidate features (diurnal_sin is shown to illustrate the temporal artefact; it is audit-only, not a schema column): the network/host modality inverts and recorded rate and fan-out scales differ.',624));
C.push(...figure('fig09_cross_imp.png',9,`Feature-importance rank agreement across datasets on the composite basis (Spearman ρ = ${f2(S.cross_rank_spearman)}). Points far from the diagonal are environment-specific.`,460));
C.push(...figure('fig10_evidence_lmd.png',10,'Complete candidate-pool class-divergence evidence, LMD-2023 (all rows): mutual information with the label; bar labels give Cliff’s δ or Cramér’s V, * = Holm-adjusted p < .05; colours use the effect-size clause of the Table 9 criterion only (the lift clause for rare binary flags is not drawn).',624));
C.push(...figure('fig11_evidence_mordor.png',11,'Complete candidate-pool class-divergence evidence, Mordor APT29 (weak labels, all rows); the authentication/service family cannot be positive under provenance labels (§3.1.1).',624));

// ===================== APPENDIX B =====================
// ===================== BUILD =====================
for(let i=1;i<C.length;i++){ if(C[i] instanceof Paragraph && C[i].__tcap && C[i-1] instanceof Table){ const cap=C[i]; C[i]=C[i-1]; C[i-1]=cap; } }
const doc=new Document({creator:'Milestone 2 Team',title:'AI-Driven Detection of Lateral Movement — Milestone 2',
  styles:{default:{document:{run:{font:FONT,size:20,color:INK}}},paragraphStyles:[{id:'FooterStyle',name:'Footer Style',basedOn:'Normal',run:{font:FONT,size:16,color:'888888'}}]},
  numbering:{config:[{reference:'bl',levels:[{level:0,format:LevelFormat.BULLET,text:'•',alignment:AlignmentType.LEFT,style:{paragraph:{indent:{left:420,hanging:240}}}}]}]},
  sections:[{properties:{page:{size:{width:12240,height:15840},margin:{top:900,bottom:900,left:1150,right:1150}}},
    footers:{default:new Footer({children:[new Paragraph({style:'FooterStyle',alignment:AlignmentType.CENTER,children:[new TextRun({text:'AI-Driven Detection of Lateral Movement — Milestone 2   •   Page ',font:FONT,size:16,color:'888888'}),new TextRun({children:[PageNumber.CURRENT],font:FONT,size:16,color:'888888'})]})]})},
    children:C}]});
Packer.toBuffer(doc).then(buf=>{fs.writeFileSync(ROOT+'/Milestone2_Report.docx',buf);console.log('WROTE',buf.length);});
